DROP TABLE IF EXISTS message, contact, assignment;

CREATE TABLE IF NOT EXISTS message(Id INT PRIMARY KEY AUTO_INCREMENT, Content TEXT, Receiver VARCHAR(255), Sender VARCHAR(255), MessageTimestamp VARCHAR(255), IsRead VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact(Id INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS assignment(Id INT PRIMARY KEY AUTO_INCREMENT, Name VARCHAR(255), Latitude VARCHAR(255), Longitude VARCHAR(255), Region TEXT, Agents VARCHAR(255), Sender VARCHAR(255), ExternalMission VARCHAR(255), Description TEXT, Timespan VARCHAR(255), Status VARCHAR(255), Cameraimage MEDIUMBLOB, Streetname VARCHAR(255), Sitename VARCHAR(255), Timestamp VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS queue(Id INT NOT NULL, ContactId INT, JSONString TEXT, FOREIGN KEY (ContactId) REFERENCES contact(Id), PRIMARY KEY(Id)) ENGINE=INNODB;
CREATE TABLE zoo (id TINYINT NOT NULL AUTO INCREMENT, name VARCHAR(50) NOT NULL, FK_species TINYINT(4) NOT NULL, INDEX (FK_species), FOREIGN KEY (FK_species) REFERENCES species (id), PRIMARY KEY(id)) ENGINE=INNODB;
